export interface ProductSpecs {
  minOrder: string;
  turnaround: string;
  sizes: string;
  printing: string;
}

export interface Product {
  slug: string;
  productCode: string;
  name: string;
  description: string;
  longDescription: string;
  idealFor: string;
  image: string;
  images: string[];
  alt: string;
  sport: string;
  sportSlug: string;
  fabric: string;
  specs: ProductSpecs;
  features: string[];
  customOptions: string[];
}


export const allProducts: Product[] = [
  // ── Soccer ───────────────────────────────────────────────────────────
  {
    slug: "custom-soccer-kit",
    productCode: "BHS-SK-001",
    name: "Custom Soccer Kit",
    description:
      "Our custom soccer kits are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom soccer kits.",
    longDescription:
      "Fully customizable jerseys and shorts with player names, numbers, and logos using full-color dye-sublimation printing. Lightweight, stretchable, and quick-drying for peak performance on the field.",
    idealFor: "School teams, soccer clubs, academies & corporate leagues",
    image: "/ranges/soccer/custom-soccer-kit.webp",
    images: [
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-1.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-2.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-3.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-4.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-5.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-6.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-7.webp",
      "/products/soccer/custom-soccer-kit/custom-soccer-kit-8.webp",
    ],
    alt: "Custom Soccer Kit",
    sport: "Soccer",
    sportSlug: "soccer",
    fabric: "100% Cool-Dry Polyester Interlock or Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Full kit: jersey & shorts included",
      "100% Cool-Dry Polyester, maximum breathability & moisture management",
      "Full-color dye-sublimation, no color limits, no fading or peeling",
      "Lightweight, stretchable & quick-drying for peak performance",
      "UPF 50+ sun protection",
      "Strong stitching throughout for long-term durability",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Player names, squad numbers & logos, wash-resistant",
      "Team name & club crest",
      "Sponsor logo placement",
      "Free professional design artwork included",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-soccer-jerseys",
    productCode: "BHS-SJ-001",
    name: "Custom Soccer Jerseys",
    description:
      "Our custom soccer jerseys are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom soccer jerseys.",
    longDescription:
      "These jerseys empower your team with customizable athletic wear that stays vibrant wash after wash. Lightweight, stretchable, and quick-drying for peak comfort on the field, ideal for school teams, soccer clubs, academies, and corporate leagues.",
    idealFor: "School teams, soccer clubs, academies & corporate leagues",
    image: "/ranges/soccer/custom-soccer-jerseys.webp",
    images: [
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-1.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-2.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-3.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-4.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-5.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-6.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-7.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-8.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-9.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-10.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-11.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-12.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-13.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-14.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-15.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-16.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-17.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-18.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-19.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-20.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-21.webp",
      "/products/soccer/custom-soccer-jerseys/custom-soccer-jerseys-22.webp",
    ],
    alt: "Custom Soccer Jerseys",
    sport: "Soccer",
    sportSlug: "soccer",
    fabric: "100% Cool-Dry Polyester Interlock or Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Fully sublimated, unlimited colours & logos",
      "100% Cool-Dry Polyester for breathability & moisture management",
      "Lightweight, stretchable & quick-drying",
      "UPF 50+ sun protection",
      "Ergonomic athletic fit",
      "Colour-fast inks, won't crack or fade wash after wash",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player names & squad numbers",
      "Free professional design included",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-shorts",
    productCode: "BHS-SS-001",
    name: "Custom Soccer Shorts",
    description:
      "Custom soccer shorts designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom soccer shorts.",
    longDescription:
      "Designed to complete your team kit with a professional, consistent look. Full-color dye-sublimation printing ensures your team colors and branding look sharp and stay vibrant. Ideal for school teams, soccer clubs, and academies.",
    idealFor: "School teams, soccer clubs, academies & corporate leagues",
    image: "/ranges/soccer/custom-soccer-shorts.webp",
    images: [
      "/products/soccer/custom-shorts/custom-shorts-1.webp",
      "/products/soccer/custom-shorts/custom-shorts-2.webp",
      "/products/soccer/custom-shorts/custom-shorts-3.webp",
      "/products/soccer/custom-shorts/custom-shorts-4.webp",
      "/products/soccer/custom-shorts/custom-shorts-5.webp",
    ],
    alt: "Custom Soccer Shorts",
    sport: "Soccer",
    sportSlug: "soccer",
    fabric: "100% Cool-Dry Polyester or Micro Mesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Elastic waistband with adjustable drawstring",
      "Lightweight & breathable mesh fabric",
      "Full sublimation, matches your kit exactly",
      "UPF 50+ protection",
      "Unlimited color and graphic possibilities",
      "Fade-resistant sublimation printing",
    ],
    customOptions: [
      "Fully sublimated to match your jersey",
      "Team name & player number",
      "Sponsor logo placement",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-socks-2",
    productCode: "BHS-SC-001",
    name: "Custom Soccer Socks",
    description:
      "Our custom soccer socks are designed according to your exact requirements and best suited to match your team's colors. Empower your team with our custom soccer socks.",
    longDescription:
      "Complete your team's kit with matching custom socks. Dye-sublimation printing keeps colors vibrant wash after wash. Reinforced construction for durability on the pitch, available in youth and adult sizing.",
    idealFor: "School teams, soccer clubs, academies & corporate leagues",
    image: "/ranges/soccer/custom-soccer-socks.webp",
    images: [
      "/products/soccer/custom-socks-2/custom-socks-2-1.webp",
      "/products/soccer/custom-socks-2/custom-socks-2-2.webp",
      "/products/soccer/custom-socks-2/custom-socks-2-3.webp",
      "/products/soccer/custom-socks-2/custom-socks-2-4.webp",
      "/products/soccer/custom-socks-2/custom-socks-2-5.webp",
    ],
    alt: "Custom Soccer Socks",
    sport: "Soccer",
    sportSlug: "soccer",
    fabric: "High-Performance Nylon / Polyester / Spandex Blend",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "High-performance blend of nylon, polyester, and spandex",
      "Reinforced heel and toe construction",
      "Elastic cuff stays up during play",
      "Colour-fast sublimation printing",
      "Multiple sizes: youth through adult",
      "Moisture-wicking for all-day comfort",
    ],
    customOptions: [
      "Team colours & club crest",
      "Player name or number on cuff",
      "Sponsor logo placement",
      "Free design artwork",
      "Youth and adult sizing available",
    ],
  },
  {
    slug: "custom-goalkeeper-jersey",
    productCode: "BHS-GK-001",
    name: "Custom Goalkeeper Jersey",
    description:
      "Custom goalkeeper jerseys are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom goalkeeper jerseys.",
    longDescription:
      "Built for goalkeepers who demand standout style and performance. Premium moisture-wicking polyester or micro mesh with full-color sublimation, unlimited colors and graphics for a truly unique look on the field.",
    idealFor: "School, club, and professional league goalkeepers",
    image: "/ranges/soccer/custom-goalkeeper-jersey.webp",
    images: [
      "/products/soccer/custom-goalkeeper-jersey/custom-goalkeeper-jersey-1.webp",
      "/products/soccer/custom-goalkeeper-jersey/custom-goalkeeper-jersey-2.webp",
      "/products/soccer/custom-goalkeeper-jersey/custom-goalkeeper-jersey-3.webp",
      "/products/soccer/custom-goalkeeper-jersey/custom-goalkeeper-jersey-4.webp",
      "/products/soccer/custom-goalkeeper-jersey/custom-goalkeeper-jersey-5.webp",
    ],
    alt: "Custom Goalkeeper Jersey",
    sport: "Soccer",
    sportSlug: "soccer",
    fabric: "Premium Moisture-Wicking Polyester or Micro Mesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Premium moisture-wicking polyester or micro mesh",
      "Full sublimation, unlimited colors and graphics",
      "Breathable, durable fabric for flexibility and protection",
      "Distinct goalkeeper styling to stand out on the field",
      "UPF 50+ sun protection",
      "Colour-fast inks, won't crack or fade",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Player name & number",
      "Club crest & sponsor logos",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },

  // ── Rugby ─────────────────────────────────────────────────────────────
  {
    slug: "custom-rugby-kit",
    productCode: "BHS-RK-001",
    name: "Custom Rugby Kit",
    description:
      "Our custom rugby kits are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom rugby kits.",
    longDescription:
      "Built for the demands of contact sport. Full-color dye-sublimation printing with strong stitching, stretchable fabric, and quick-drying properties. Fully customizable with player names, numbers, and logos.",
    idealFor: "School teams, rugby clubs, academies & corporate leagues",
    image: "/ranges/rugby/custom-rugby-kit.webp",
    images: [
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-1.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-2.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-3.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-4.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-5.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-6.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-7.webp",
      "/products/rugby/custom-rugby-kit/custom-rugby-kit-8.webp",
    ],
    alt: "Custom Rugby Kit",
    sport: "Rugby",
    sportSlug: "rugby",
    fabric: "100% Polyester, Scuba Performance Fabric or Mesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "100% Polyester, scuba performance fabric or mesh",
      "Full-color dye-sublimation, no fading or peeling",
      "Strong stitching for contact sport durability",
      "Moisture-wicking, quick-drying performance fabric",
      "Stretchable construction for full range of motion",
      "UPF 50+ sun protection",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player names & squad numbers, wash-resistant",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },

  // ── Basketball ────────────────────────────────────────────────────────
  {
    slug: "custom-basketball-jersey",
    productCode: "BHS-BJ-001",
    name: "Custom Basketball Jersey",
    description:
      "Our custom basketball jerseys are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom basketball jerseys.",
    longDescription:
      "Fully dye sublimated with no limit on colors and logos. Numbers, names, and logos that won't come out in the wash, even better than traditional basketball jerseys. Ideal for school teams, basketball leagues, and organizations.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-basketball-jersey.webp",
    images: [
      "/products/basketball/custom-basketball-jersey/custom-basketball-jersey-1.webp",
      "/products/basketball/custom-basketball-jersey/custom-basketball-jersey-2.webp",
      "/products/basketball/custom-basketball-jersey/custom-basketball-jersey-3.webp",
      "/products/basketball/custom-basketball-jersey/custom-basketball-jersey-4.webp",
      "/products/basketball/custom-basketball-jersey/custom-basketball-jersey-5.webp",
    ],
    alt: "Custom Basketball Jersey",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Fully dye sublimated, no limit on colors and logos",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Numbers, names & logos that won't wash out",
      "Lightweight for maximum court mobility",
      "Moisture-wicking performance fabric",
      "Superior durability vs. traditional basketball jerseys",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-basketball-shorts",
    productCode: "BHS-BT-001",
    name: "Custom Basketball Shorts",
    description:
      "Our custom basketball shorts are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom basketball shorts.",
    longDescription:
      "Fully dye sublimated with no limit on colors and logos. Designed to complement your team jersey with a sharp, consistent look. Full-color dye-sublimation printing keeps your team looking and performing their best.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-basketball-shorts.webp",
    images: [
      "/products/basketball/custom-basketball-shorts/custom-basketball-shorts-1.webp",
      "/products/basketball/custom-basketball-shorts/custom-basketball-shorts-2.webp",
      "/products/basketball/custom-basketball-shorts/custom-basketball-shorts-3.webp",
      "/products/basketball/custom-basketball-shorts/custom-basketball-shorts-4.webp",
      "/products/basketball/custom-basketball-shorts/custom-basketball-shorts-5.webp",
    ],
    alt: "Custom Basketball Shorts",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Fully dye sublimated, no limit on colors and logos",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Elasticated waistband with drawstring",
      "Side pockets included",
      "Moisture-wicking & quick-drying",
      "Extended knee-length cut",
    ],
    customOptions: [
      "Sublimated to match your jersey",
      "Team name & player number",
      "Sponsor logo placement",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-basketball-uniform",
    productCode: "BHS-BU-001",
    name: "Custom Basketball Uniform",
    description:
      "Our custom basketball uniforms are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom basketball uniforms.",
    longDescription:
      "Fully dye sublimated with no limit on colors and logos. Numbers, names, and logos that won't come out in the wash, built for school teams, basketball leagues, and organizations.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-basketball-uniform.webp",
    images: [
      "/products/basketball/custom-basketball-uniform/custom-basketball-uniform-1.webp",
      "/products/basketball/custom-basketball-uniform/custom-basketball-uniform-2.webp",
      "/products/basketball/custom-basketball-uniform/custom-basketball-uniform-3.webp",
      "/products/basketball/custom-basketball-uniform/custom-basketball-uniform-4.webp",
      "/products/basketball/custom-basketball-uniform/custom-basketball-uniform-5.webp",
    ],
    alt: "Custom Basketball Uniform",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Full uniform: jersey & shorts included",
      "Fully dye sublimated, no limit on colors and logos",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Numbers, names & logos that won't wash out",
      "Moisture-wicking performance fabric",
      "Superior durability vs. traditional basketball jerseys",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-reversible-basketball-jersey",
    productCode: "BHS-RBJ-001",
    name: "Custom Reversible Basketball Jersey",
    description:
      "Our custom reversible basketball jerseys are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom reversible basketball jerseys.",
    longDescription:
      "Fully dye sublimated with unlimited color and logo options, two complete looks in one jersey. Numbers, names, and logos with wash-resistant application. Enhanced durability compared to traditional basketball jerseys.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-reversible-basketball-jersey.webp",
    images: [
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-1.webp",
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-2.webp",
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-3.webp",
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-4.webp",
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-5.webp",
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-6.webp",
      "/products/basketball/custom-reversible-basketball-jersey/custom-reversible-basketball-jersey-7.webp",
    ],
    alt: "Custom Reversible Basketball Jersey",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Reversible, two complete looks in one jersey",
      "Fully dye sublimated, no limit on colors and logos",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Numbers, names & logos with wash-resistant application",
      "Moisture-wicking performance fabric",
      "Enhanced durability vs. traditional basketball jerseys",
    ],
    customOptions: [
      "Two-sided custom design",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-shooting-hoodies",
    productCode: "BHS-SH-001",
    name: "Custom Shooting Hoodies",
    description:
      "Custom basketball shooting hoodies designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom basketball shooting hoodies.",
    longDescription:
      "Available in long sleeve and short sleeve options. Fully dye sublimated with no limit on colors and logos. Numbers, names, and logos that won't come out in the wash, superior durability for training and game day.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-shooting-hoodies.webp",
    images: [
      "/products/basketball/custom-shooting-hoodies/custom-shooting-hoodies-1.webp",
      "/products/basketball/custom-shooting-hoodies/custom-shooting-hoodies-2.webp",
      "/products/basketball/custom-shooting-hoodies/custom-shooting-hoodies-3.webp",
      "/products/basketball/custom-shooting-hoodies/custom-shooting-hoodies-4.webp",
      "/products/basketball/custom-shooting-hoodies/custom-shooting-hoodies-5.webp",
    ],
    alt: "Custom Shooting Hoodies",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Available in long sleeve & short sleeve options",
      "Fully dye sublimated, no limit on colors and logos",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Numbers, names & logos that won't wash out",
      "Moisture-wicking performance fabric",
      "Attached hood with full sublimation",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-shooting-shirts",
    productCode: "BHS-ST-001",
    name: "Custom Shooting Shirts",
    description:
      "Custom basketball shooting shirts designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom basketball shooting shirt.",
    longDescription:
      "Fully dye sublimated with no limit on colors and logos. Numbers, names, and logos with wash-fast application, superior durability for school teams, basketball leagues, and organizations.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-shooting-shirts.webp",
    images: [
      "/products/basketball/custom-shooting-shirts/custom-shooting-shirts-1.webp",
      "/products/basketball/custom-shooting-shirts/custom-shooting-shirts-2.webp",
      "/products/basketball/custom-shooting-shirts/custom-shooting-shirts-3.webp",
      "/products/basketball/custom-shooting-shirts/custom-shooting-shirts-4.webp",
      "/products/basketball/custom-shooting-shirts/custom-shooting-shirts-5.webp",
      "/products/basketball/custom-shooting-shirts/custom-shooting-shirts-6.webp",
    ],
    alt: "Custom Shooting Shirts",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Fully dye sublimated, no limit on colors and logos",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Numbers, names & logos with wash-fast application",
      "Lightweight & moisture-wicking",
      "Ergonomic athletic fit for shooting motion",
      "Superior durability vs. traditional basketball jerseys",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-shooting-sleeves",
    productCode: "BHS-SL-001",
    name: "Custom Shooting Sleeves",
    description:
      "Custom shooting sleeves, lightweight, breathable, and built for performance. Fully customizable with your team's logos, names, and graphics.",
    longDescription:
      "Made with dry-fit stretch fabric for full mobility. Fully dye sublimated with no limit on colors and logos. Numbers, names, and logos with wash-resistant application, designed for basketball leagues, school teams, and organizations.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/custom-shooting-sleeves.webp",
    images: [
      "/products/basketball/custom-shooting-sleeves/custom-shooting-sleeves-1.webp",
      "/products/basketball/custom-shooting-sleeves/custom-shooting-sleeves-2.webp",
      "/products/basketball/custom-shooting-sleeves/custom-shooting-sleeves-3.webp",
      "/products/basketball/custom-shooting-sleeves/custom-shooting-sleeves-4.webp",
      "/products/basketball/custom-shooting-sleeves/custom-shooting-sleeves-5.webp",
      "/products/basketball/custom-shooting-sleeves/custom-shooting-sleeves-6.webp",
    ],
    alt: "Custom Shooting Sleeves",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "Dry-Fit Stretch Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Dry-fit stretch fabric for full mobility",
      "Fully dye sublimated, no limit on colors and logos",
      "Numbers, names & logos with wash-resistant application",
      "Lightweight & breathable",
      "Compression fit for support during play",
      "Superior durability vs. traditional sleeves",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Youth and adult sizing",
    ],
  },
  {
    slug: "v-neck-basketball-jersey",
    productCode: "BHS-VJ-001",
    name: "V Neck Basketball Jersey",
    description:
      "Custom V-neck basketball jerseys designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom V-neck basketball jerseys.",
    longDescription:
      "Full dye sublimation with unlimited color options, numbers, names, and logos with permanent wash-resistance. Enhanced performance vs. traditional basketball jerseys.",
    idealFor: "Basketball clubs, leagues, school teams & organizations",
    image: "/ranges/basketball/v-neck-basketball-jersey.webp",
    images: [
      "/products/basketball/v-neck-basketball-jersey/v-neck-basketball-jersey-1.webp",
      "/products/basketball/v-neck-basketball-jersey/v-neck-basketball-jersey-2.webp",
      "/products/basketball/v-neck-basketball-jersey/v-neck-basketball-jersey-3.webp",
      "/products/basketball/v-neck-basketball-jersey/v-neck-basketball-jersey-4.webp",
      "/products/basketball/v-neck-basketball-jersey/v-neck-basketball-jersey-5.webp",
      "/products/basketball/v-neck-basketball-jersey/v-neck-basketball-jersey-6.webp",
    ],
    alt: "V Neck Basketball Jersey",
    sport: "Basketball",
    sportSlug: "basketball",
    fabric: "100% Cool Dry Polyester Interlock / Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Classic V-neck collar design",
      "Full dye sublimation, unlimited color options",
      "100% Cool Dry Polyester Interlock or Micromesh",
      "Numbers, names & logos with permanent wash-resistance",
      "Moisture-wicking performance fabric",
      "Enhanced performance vs. traditional basketball jerseys",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },

  // ── Cricket ───────────────────────────────────────────────────────────
  {
    slug: "custom-cricket-kit",
    productCode: "BHS-CK-001",
    name: "Custom Cricket Kit",
    description:
      "Our custom cricket kits are designed according to your exact requirements and best suited to match your team's brand image. Empower your team with our custom cricket kits.",
    longDescription:
      "Full-color dye-sublimation printing ensures vibrant, wash-resistant colors, lightweight, stretchable, and quick-drying for peak comfort on the field. Ideal for school teams, cricket clubs, academies, and leagues.",
    idealFor: "School teams, cricket clubs, academies & leagues",
    image: "/ranges/cricket/custom-cricket-kit.webp",
    images: [
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-1.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-2.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-3.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-4.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-5.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-6.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-7.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-8.webp",
      "/products/cricket/custom-cricket-kit/custom-cricket-kit-9.webp",
    ],
    alt: "Custom Cricket Kit",
    sport: "Cricket",
    sportSlug: "cricket",
    fabric: "100% Cool-Dry Polyester Interlock or Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "UPF 50+ sun protection, all-day outdoor play",
      "100% Cool-Dry Polyester, maximum breathability",
      "Full-color dye-sublimation, no fading or peeling",
      "Lightweight, stretchable & quick-drying",
      "Vibrant wash-resistant colours",
      "Fully customizable with player names, numbers, logos",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & squad number",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },

  // ── 7v7 Football ──────────────────────────────────────────────────────
  {
    slug: "custom-7v7-uniforms",
    productCode: "BHS-7U-001",
    name: "Custom 7v7 Uniforms",
    description:
      "Custom 7v7 Uniforms with Hooded Top. Made from the finest materials for extra durability and style, our custom 7v7 uniforms are available in a wide range of colors, styles, and sizes.",
    longDescription:
      "Fully sublimated to ensure your design NEVER shrinks, fades, or tarnishes. Available in compression or Dri-Fit fabrics with logos, names, and numbers for youth and adult consumers.",
    idealFor: "7V7 organizations, leagues & teams",
    image: "/ranges/7v7-football/custom-7v7-uniforms.webp",
    images: [
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-1.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-2.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-3.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-4.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-5.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-6.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-7.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-8.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-9.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-10.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-11.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-12.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-13.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-14.webp",
      "/products/7v7-football/custom-7v7-uniforms/custom-7v7-uniforms-15.webp",
    ],
    alt: "Custom 7v7 Uniforms",
    sport: "7v7 Football",
    sportSlug: "7v7-football",
    fabric: "High-Performance Dri-Fit or Compression Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Fully sublimated, design NEVER shrinks, fades, or tarnishes",
      "High-performance Dri-Fit or compression fabric options",
      "Available in a wide range of colors, styles, and sizes",
      "Logos, names & numbers included",
      "Youth and Adult sizes available",
      "High-quality durable fabric",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Club crest & sponsor logos",
      "Player name & number",
      "Free design artwork",
      "Youth & adult sizing",
    ],
  },
  {
    slug: "custom-7v7-hooded-uniforms",
    productCode: "BHS-7H-001",
    name: "Custom 7v7 Hooded Uniforms",
    description:
      "Custom 7v7 Uniforms with Hooded Top. Made from the finest materials for extra durability and style, our custom 7v7 uniforms are available in a wide range of colors, styles, and sizes.",
    longDescription:
      "Fully sublimated to ensure your design NEVER shrinks, fades, or tarnishes. High-performance compression or Dri-Fit fabric choices with logos, names, and numbers.",
    idealFor: "7V7 organizations, leagues & teams",
    image: "/ranges/7v7-football/custom-7v7-hooded-uniforms.webp",
    images: [
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-1.webp",
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-2.webp",
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-3.webp",
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-4.webp",
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-5.webp",
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-6.webp",
      "/products/7v7-football/custom-7v7-hooded-uniforms/custom-7v7-hooded-uniforms-7.webp",
    ],
    alt: "Custom 7v7 Hooded Uniforms",
    sport: "7v7 Football",
    sportSlug: "7v7-football",
    fabric: "High-Performance Dri-Fit or Compression Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Attached performance hood, fully sublimated",
      "Fully sublimated, design NEVER shrinks, fades, or tarnishes",
      "High-performance Dri-Fit or compression fabric",
      "Moisture-wicking technology",
      "Available in hooded & sleeveless hooded styles",
      "High-quality fabric for long-lasting vibrant designs",
    ],
    customOptions: [
      "Full sublimation on jersey and hood",
      "Logos, names & numbers",
      "Club crest & sponsor logos",
      "Free design artwork",
      "Youth & adult sizing",
    ],
  },
  {
    slug: "custom-7v7-sleeveless-hooded-jerseys",
    productCode: "BHS-7SH-001",
    name: "Custom 7v7 Sleeveless Hooded Jerseys",
    description:
      "Custom Flag jersey. Made from the finest materials for extra durability and style, our custom 7v7 jerseys are available in a wide range of colors, styles, and sizes.",
    longDescription:
      "Fully sublimated to ensure your design NEVER shrinks, fades, or tarnishes. Durable construction for long-lasting vibrancy, intended for 7V7 organizations, leagues, and teams.",
    idealFor: "7V7 organizations, leagues & teams",
    image: "/ranges/7v7-football/custom-7v7-sleeveless-hooded-jerseys.webp",
    images: [
      "/products/7v7-football/custom-7v7-sleeveless-hooded-jerseys/custom-7v7-sleeveless-hooded-jerseys-1.webp",
      "/products/7v7-football/custom-7v7-sleeveless-hooded-jerseys/custom-7v7-sleeveless-hooded-jerseys-2.webp",
      "/products/7v7-football/custom-7v7-sleeveless-hooded-jerseys/custom-7v7-sleeveless-hooded-jerseys-3.webp",
      "/products/7v7-football/custom-7v7-sleeveless-hooded-jerseys/custom-7v7-sleeveless-hooded-jerseys-4.webp",
      "/products/7v7-football/custom-7v7-sleeveless-hooded-jerseys/custom-7v7-sleeveless-hooded-jerseys-5.webp",
    ],
    alt: "Custom 7v7 Sleeveless Hooded Jerseys",
    sport: "7v7 Football",
    sportSlug: "7v7-football",
    fabric: "High-Performance Dri-Fit or Compression Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth & Adult",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Sleeveless hooded design for maximum mobility",
      "Fully sublimated, design NEVER shrinks, fades, or tarnishes",
      "High-performance Dri-Fit or compression fabric",
      "Logos, names & numbers included",
      "Durable construction for long-lasting vibrancy",
      "Available in Youth and Adult sizes",
    ],
    customOptions: [
      "Full sublimation on jersey and hood",
      "Logos, names & numbers",
      "Club crest & sponsor logos",
      "Free design artwork",
      "Youth & adult sizing",
    ],
  },
  {
    slug: "custom-7v7-sleeveless-jerseys",
    productCode: "BHS-7SL-001",
    name: "Custom 7v7 Sleeveless Jerseys",
    description:
      "Custom Flag jersey. Made from the finest materials for extra durability and style, our custom 7v7 jerseys are available in a wide range of colors, styles, and sizes.",
    longDescription:
      "Fully sublimated to ensure your design NEVER shrinks, fades, or tarnishes. High-performance Dri-Fit or compression fabric, designed for 7V7 organizations, leagues, and teams.",
    idealFor: "7V7 organizations, leagues & teams",
    image: "/ranges/7v7-football/custom-7v7-sleeveless-jerseys.webp",
    images: [
      "/products/7v7-football/custom-7v7-sleeveless-jerseys/custom-7v7-sleeveless-jerseys-1.webp",
      "/products/7v7-football/custom-7v7-sleeveless-jerseys/custom-7v7-sleeveless-jerseys-2.webp",
      "/products/7v7-football/custom-7v7-sleeveless-jerseys/custom-7v7-sleeveless-jerseys-3.webp",
      "/products/7v7-football/custom-7v7-sleeveless-jerseys/custom-7v7-sleeveless-jerseys-4.webp",
      "/products/7v7-football/custom-7v7-sleeveless-jerseys/custom-7v7-sleeveless-jerseys-5.webp",
    ],
    alt: "Custom 7v7 Sleeveless Jerseys",
    sport: "7v7 Football",
    sportSlug: "7v7-football",
    fabric: "High-Performance Dri-Fit or Compression Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Classic sleeveless cut for maximum mobility",
      "Fully sublimated, design NEVER shrinks, fades, or tarnishes",
      "High-performance Dri-Fit or compression fabric",
      "Logos, names & numbers included",
      "Durable construction for long-lasting vibrancy",
      "Available in Youth and Adult sizes",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Logos, names & numbers",
      "Club crest & sponsor logos",
      "Free design artwork",
      "Youth & adult sizing",
    ],
  },
  {
    slug: "custom-7v7-football-shorts",
    productCode: "BHS-7FS-001",
    name: "Custom 7v7 Football Shorts",
    description:
      "Made from the finest materials for extra durability and style, our custom 7v7 shorts are available in a wide range of colors, styles, and sizes.",
    longDescription:
      "Fully sublimated to ensure your design NEVER shrinks, fades, or tarnishes. High-performance Dri-Fit or compression fabrics, fully customizable with logos, names, and numbers.",
    idealFor: "7V7 organizations, leagues & teams",
    image: "/ranges/7v7-football/custom-7v7-football-shorts.webp",
    images: [
      "/products/7v7-football/custom-7v7-football-shorts/custom-7v7-football-shorts-1.webp",
      "/products/7v7-football/custom-7v7-football-shorts/custom-7v7-football-shorts-2.webp",
      "/products/7v7-football/custom-7v7-football-shorts/custom-7v7-football-shorts-3.webp",
      "/products/7v7-football/custom-7v7-football-shorts/custom-7v7-football-shorts-4.webp",
      "/products/7v7-football/custom-7v7-football-shorts/custom-7v7-football-shorts-5.webp",
    ],
    alt: "Custom 7v7 Football Shorts",
    sport: "7v7 Football",
    sportSlug: "7v7-football",
    fabric: "High-Performance Dri-Fit or Compression Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Fully sublimated, design NEVER shrinks, fades, or tarnishes",
      "High-performance Dri-Fit or compression fabrics",
      "Wide range of colors, styles, and sizes",
      "Logos, names & numbers included",
      "Available in Youth and Adult sizes",
      "Durable construction for long-lasting use",
    ],
    customOptions: [
      "Fully sublimated to match your jersey",
      "Logos, names & numbers",
      "Sponsor logo placement",
      "Free design artwork",
      "Youth & adult sizing",
    ],
  },

  // ── Baseball ──────────────────────────────────────────────────────────
  {
    slug: "custom-baseball-uniforms",
    productCode: "BHS-BBU-001",
    name: "Custom Baseball Uniforms",
    description:
      "Custom Baseball Uniforms fully customized with your team's colors, logos, names, and numbers. Made with breathable, premium polyester for comfort, durability, and all-day performance.",
    longDescription:
      "100% cool-dry polyester mesh/interlock for breathable on-field comfort. Customization via sublimation with unlimited color and graphic possibilities, breathable yet durable fabric designed for maximum flexibility and protection.",
    idealFor: "School teams, baseball clubs, local leagues & academies",
    image: "/ranges/baseball/custom-baseball-uniforms.webp",
    images: [
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-1.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-2.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-3.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-4.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-5.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-6.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-7.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-8.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-9.webp",
      "/products/baseball/custom-baseball-uniforms/custom-baseball-uniforms-10.webp",
    ],
    alt: "Custom Baseball Uniforms",
    sport: "Baseball",
    sportSlug: "baseball",
    fabric: "100% Cool-Dry Polyester Mesh / Interlock",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Full uniform: jersey & pants included",
      "100% cool-dry polyester mesh/interlock",
      "Unlimited color and graphic possibilities via sublimation",
      "Breathable yet durable for maximum flexibility",
      "Won't crack or fade with high-quality printing",
      "Ideal for school teams, clubs, leagues & academies",
    ],
    customOptions: [
      "Team colours, logos, names & numbers",
      "Club crest & sponsor logos",
      "Player name & squad number",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "2-button-baseball-jerseys",
    productCode: "BHS-BB2-001",
    name: "2-Button Baseball Jerseys",
    description:
      "Two button baseball jerseys fully customized with your team's colors, logos, names, and numbers. Made with breathable, premium polyester for comfort, durability, and all-day performance.",
    longDescription:
      "100% cool-dry polyester mesh/interlock for breathable on-field comfort. High-quality sublimation printing with unlimited colors and graphics, durable fabric designed for maximum flexibility and protection.",
    idealFor: "School teams, baseball clubs, local leagues & academies",
    image: "/ranges/baseball/2-button-baseball-jerseys.webp",
    images: [
      "/products/baseball/2-button-baseball-jerseys/2-button-baseball-jerseys-1.webp",
      "/products/baseball/2-button-baseball-jerseys/2-button-baseball-jerseys-2.webp",
      "/products/baseball/2-button-baseball-jerseys/2-button-baseball-jerseys-3.webp",
      "/products/baseball/2-button-baseball-jerseys/2-button-baseball-jerseys-4.webp",
    ],
    alt: "2-Button Baseball Jerseys",
    sport: "Baseball",
    sportSlug: "baseball",
    fabric: "100% Cool-Dry Polyester Mesh / Interlock",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Classic 2-button placket design",
      "100% cool-dry polyester mesh/interlock",
      "High-quality sublimation, unlimited colors & graphics",
      "Breathable, durable fabric for flexibility & protection",
      "Won't crack or fade",
      "Ideal for school teams, clubs, leagues & academies",
    ],
    customOptions: [
      "Team colours, logos, names & numbers",
      "Club crest & sponsor logos",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "baseball-crew-neck-jerseys",
    productCode: "BHS-BBcn-001",
    name: "Baseball Crew Neck Jerseys",
    description:
      "Crew neck baseball jerseys fully customized with team colors, logos, names, and numbers. Made with breathable, premium polyester for comfort, durability, and all-day performance.",
    longDescription:
      "100% cool-dry polyester mesh/interlock for breathable on-field comfort. Unlimited colors and graphics with durable sublimation printing, breathable yet durable for maximum flexibility and protection.",
    idealFor: "School teams, baseball clubs, local leagues & academies",
    image: "/ranges/baseball/baseball-crew-neck-jerseys.webp",
    images: [
      "/products/baseball/baseball-crew-neck-jerseys/baseball-crew-neck-jerseys-1.webp",
      "/products/baseball/baseball-crew-neck-jerseys/baseball-crew-neck-jerseys-2.webp",
      "/products/baseball/baseball-crew-neck-jerseys/baseball-crew-neck-jerseys-3.webp",
      "/products/baseball/baseball-crew-neck-jerseys/baseball-crew-neck-jerseys-4.webp",
      "/products/baseball/baseball-crew-neck-jerseys/baseball-crew-neck-jerseys-5.webp",
    ],
    alt: "Baseball Crew Neck Jerseys",
    sport: "Baseball",
    sportSlug: "baseball",
    fabric: "100% Cool-Dry Polyester Mesh / Interlock",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Classic crew neck design",
      "100% cool-dry polyester mesh/interlock",
      "Unlimited colors & graphics with durable sublimation",
      "Breathable yet durable for max flexibility & protection",
      "Won't crack or fade",
      "Ideal for school teams, clubs, leagues & academies",
    ],
    customOptions: [
      "Team colours, logos, names & numbers",
      "Club crest & sponsor logos",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "baseball-v-neck-jerseys",
    productCode: "BHS-BBvn-001",
    name: "Baseball V-Neck Jerseys",
    description:
      "V-neck baseball jerseys fully customized with team colors, logos, names, and numbers. Made with breathable, premium polyester for comfort, durability, and all-day performance.",
    longDescription:
      "100% cool-dry polyester mesh/interlock for breathable on-field comfort. Unlimited color and graphic possibilities with long-lasting print durability, breathable yet durable fabric designed for maximum flexibility and protection.",
    idealFor: "School teams, baseball clubs, local leagues & academies",
    image: "/ranges/baseball/baseball-v-neck-jerseys.webp",
    images: [
      "/products/baseball/baseball-v-neck-jerseys/baseball-v-neck-jerseys-1.webp",
      "/products/baseball/baseball-v-neck-jerseys/baseball-v-neck-jerseys-2.webp",
      "/products/baseball/baseball-v-neck-jerseys/baseball-v-neck-jerseys-3.webp",
      "/products/baseball/baseball-v-neck-jerseys/baseball-v-neck-jerseys-4.webp",
    ],
    alt: "Baseball V-Neck Jerseys",
    sport: "Baseball",
    sportSlug: "baseball",
    fabric: "100% Cool-Dry Polyester Mesh / Interlock",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Classic V-neck collar design",
      "100% cool-dry polyester mesh/interlock",
      "Unlimited color and graphic possibilities",
      "Long-lasting print durability",
      "Breathable yet durable for max flexibility & protection",
      "Ideal for school teams, clubs, leagues & academies",
    ],
    customOptions: [
      "Team colours, logos, names & numbers",
      "Club crest & sponsor logos",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "full-button-baseball-jerseys",
    productCode: "BHS-BBfb-001",
    name: "Full Button Baseball Jerseys",
    description:
      "Full button baseball jerseys fully customized with your team's colors, logos, names, and numbers. Made with breathable, premium polyester for comfort, durability, and all-day performance.",
    longDescription:
      "100% cool-dry polyester mesh/interlock for breathable on-field comfort. Sublimation with unlimited color and graphic possibilities, won't crack or fade.",
    idealFor: "School teams, baseball clubs, local leagues & academies",
    image: "/ranges/baseball/full-button-baseball-jerseys.webp",
    images: [
      "/products/baseball/full-button-baseball-jerseys/full-button-baseball-jerseys-1.webp",
      "/products/baseball/full-button-baseball-jerseys/full-button-baseball-jerseys-2.webp",
      "/products/baseball/full-button-baseball-jerseys/full-button-baseball-jerseys-3.webp",
      "/products/baseball/full-button-baseball-jerseys/full-button-baseball-jerseys-4.webp",
    ],
    alt: "Full Button Baseball Jerseys",
    sport: "Baseball",
    sportSlug: "baseball",
    fabric: "100% Cool-Dry Polyester Mesh / Interlock",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Full button-down placket design",
      "100% cool-dry polyester mesh/interlock",
      "Unlimited color and graphic possibilities via sublimation",
      "Won't crack or fade, high-quality printing",
      "Breathable yet durable for max flexibility & protection",
      "Ideal for school teams, clubs, leagues & academies",
    ],
    customOptions: [
      "Team colours, logos, names & numbers",
      "Club crest & sponsor logos",
      "Free professional design artwork",
      "Men's, women's & youth sizing",
    ],
  },

  // ── MMA ───────────────────────────────────────────────────────────────
  {
    slug: "custom-mma-fight-shorts",
    productCode: "BHS-MFS-001",
    name: "Custom MMA Fight Shorts",
    description:
      "Our Custom MMA fight shorts are lightweight, flexible, and fully sublimated. Personalize colors, names, team logos, and patterns. Perfect balance of comfort, mobility, and fight-ready durability.",
    longDescription:
      "Premium satin or microfiber fabric, tear-resistant for training and competition. Personalized fighter names, gym logos, flags, and full-color graphics. Ideal for Muay Thai gyms, fighters, kickboxing, and martial arts teams.",
    idealFor: "Muay Thai gyms, fighters, kickboxing & martial arts teams",
    image: "/ranges/mma/custom-mma-fight-shorts.webp",
    images: [
      "/products/mma/custom-mma-fight-shorts/custom-mma-fight-shorts-1.webp",
      "/products/mma/custom-mma-fight-shorts/custom-mma-fight-shorts-2.webp",
      "/products/mma/custom-mma-fight-shorts/custom-mma-fight-shorts-3.webp",
    ],
    alt: "Custom MMA Fight Shorts",
    sport: "MMA",
    sportSlug: "mma",
    fabric: "Premium Satin or Microfiber Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Lightweight, flexible, and fully sublimated",
      "Premium satin or microfiber fabric",
      "Tear-resistant for training and competition",
      "Full-color sublimation, unlimited colors and logos",
      "Fighter names, gym logos, flags & custom graphics",
      "Perfect balance of comfort, mobility, and durability",
    ],
    customOptions: [
      "Fighter names & gym logos",
      "Flag & custom graphic designs",
      "Unlimited colour combinations",
      "Free design artwork",
      "Youth, women's & men's sizing",
    ],
  },
  {
    slug: "custom-rashguard",
    productCode: "BHS-MRG-001",
    name: "Custom MMA Rashguard",
    description:
      "Custom rashguards designed for combat sports, training, and team wear. Fully sublimated with no color limits, add your team's logos, names, and graphics. Made with 4-way stretch, moisture-wicking fabric for maximum comfort and protection.",
    longDescription:
      "Moisture-wicking polyester/spandex 4-way stretch fabric with anti-pilling, anti-tear, and reinforced stitching for intense training. Ideal for BJJ, MMA, wrestling, no-gi training, and fitness.",
    idealFor: "BJJ, MMA, wrestling, no-gi training & fitness",
    image: "/ranges/mma/custom-mma-rashguard.webp",
    images: [
      "/products/mma/custom-rashguard/custom-rashguard-1.webp",
      "/products/mma/custom-rashguard/custom-rashguard-2.webp",
      "/products/mma/custom-rashguard/custom-rashguard-3.webp",
      "/products/mma/custom-rashguard/custom-rashguard-4.webp",
    ],
    alt: "Custom MMA Rashguard",
    sport: "MMA",
    sportSlug: "mma",
    fabric: "Moisture-Wicking Polyester/Spandex 4-Way Stretch",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "4-way stretch fabric for full mobility",
      "Moisture-wicking polyester/spandex blend",
      "Anti-pilling, anti-tear construction",
      "Reinforced stitching for intense training",
      "Fully sublimated, no limit on colors",
      "Logos, names & graphics that won't fade",
    ],
    customOptions: [
      "Team logos, names & numbers",
      "Unlimited colour combinations",
      "Gym branding & sponsor logos",
      "Free design artwork",
      "Youth, women's & men's sizing",
    ],
  },
  {
    slug: "custom-wrestling-singlets",
    productCode: "BHS-MWS-001",
    name: "Custom Wrestling Singlets",
    description:
      "Custom wrestling singlets designed to match your team colors, style, and competitive spirit. Manufactured for maximum flexibility, strength, and all-day performance.",
    longDescription:
      "4-way stretch spandex/polyester blend for maximum mobility and comfort. Fully dye sublimated with no limit on colors and logos, reinforced stitching with stretch fabric for rigorous competition.",
    idealFor: "School teams, wrestling clubs, tournaments & organizations",
    image: "/ranges/mma/custom-wrestling-singlets.webp",
    images: [
      "/products/mma/custom-wrestling-singlets/custom-wrestling-singlets-1.webp",
      "/products/mma/custom-wrestling-singlets/custom-wrestling-singlets-2.webp",
      "/products/mma/custom-wrestling-singlets/custom-wrestling-singlets-3.webp",
    ],
    alt: "Custom Wrestling Singlets",
    sport: "MMA",
    sportSlug: "mma",
    fabric: "4-Way Stretch Spandex / Polyester Blend",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "4-way stretch spandex/polyester blend",
      "Fully dye sublimated, no limit on colors and logos",
      "Numbers, names & logos designed for wash-durability",
      "Reinforced stitching with stretch fabric",
      "Maximum mobility & comfort for competition",
      "Ideal for school teams, wrestling clubs & tournaments",
    ],
    customOptions: [
      "Team colours, logos, names & numbers",
      "Club crest & sponsor logos",
      "Free design artwork",
      "Youth, women's & men's sizing",
    ],
  },

  // ── Teamwear ──────────────────────────────────────────────────────────
  {
    slug: "custom-team-hoodies",
    productCode: "BHS-TH-001",
    name: "Custom Team Hoodies",
    description:
      "Big Hope's hoodies are made from polyester fleece with full dye-sublimation for unlimited colors, logos, and designs. Moisture-wicking, anti-bacterial, and comfy, available in pull-on, full-zip, and jacket styles.",
    longDescription:
      "100% polyester fleece (Speedo fabric), fully dye sublimated with no limit on colors and logos. High-quality fabric that withstands wear, keeping your designs vibrant for men, women, and youth.",
    idealFor: "Sports teams, training wear, fan gear & promotional branding",
    image: "/ranges/teamwear/custom-team-hoodies.webp",
    images: [
      "/products/teamwear/custom-team-hoodies/custom-team-hoodies-1.webp",
      "/products/teamwear/custom-team-hoodies/custom-team-hoodies-2.webp",
      "/products/teamwear/custom-team-hoodies/custom-team-hoodies-3.webp",
      "/products/teamwear/custom-team-hoodies/custom-team-hoodies-4.webp",
      "/products/teamwear/custom-team-hoodies/custom-team-hoodies-5.webp",
      "/products/teamwear/custom-team-hoodies/custom-team-hoodies-6.webp",
    ],
    alt: "Custom Team Hoodies",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester Fleece (Speedo Fabric)",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "100% polyester fleece, moisture-wicking & anti-bacterial",
      "Fully dye sublimated, no limit on colors and logos",
      "Available in pull-on, full-zip, and jacket styles",
      "High-quality fabric maintains vibrant designs",
      "Comfortable fit for training and casual wear",
      "Durable construction that withstands wear",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Sponsor logos & club crest",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-zipper-hoodies",
    productCode: "BHS-ZH-001",
    name: "Custom Zipper Hoodies",
    description:
      "Big Hope's zipper hoodies use polyester fleece with full dye-sublimation for unlimited colors, logos, and designs. Moisture-wicking, anti-bacterial, and comfy, available in pull-on, full-zip, and jacket styles.",
    longDescription:
      "100% polyester fleece (Speedo fabric), fully dye sublimated with no limit on colors and logos. High-quality fabric that withstands wear, keeping your designs vibrant for sports teams, training wear, fan gear, and promotional branding.",
    idealFor: "Sports teams, training wear, fan gear & promotional branding",
    image: "/ranges/teamwear/custom-zipper-hoodies.webp",
    images: [
      "/products/teamwear/custom-zipper-hoodies/custom-zipper-hoodies-1.webp",
      "/products/teamwear/custom-zipper-hoodies/custom-zipper-hoodies-2.webp",
      "/products/teamwear/custom-zipper-hoodies/custom-zipper-hoodies-3.webp",
      "/products/teamwear/custom-zipper-hoodies/custom-zipper-hoodies-4.webp",
    ],
    alt: "Custom Zipper Hoodies",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester Fleece (Speedo Fabric)",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Full-zip design for easy on/off",
      "100% polyester fleece, moisture-wicking & anti-bacterial",
      "Fully dye sublimated, no limit on colors and logos",
      "High-quality fabric that withstands wear",
      "Comfortable fit for training and casual wear",
      "Durable construction keeping designs vibrant",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Sponsor logos & club crest",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-tracksuits",
    productCode: "BHS-TS-001",
    name: "Custom Tracksuits",
    description:
      "Premium warmup sets crafted from 100% polyester fleece or Scuba fabric, fully customizable with logos, sizes, and designs. Ideal for sports teams, charities, events, and schools.",
    longDescription:
      "Fully dye sublimated with unlimited color options and logo placement. High-quality, durable construction maintaining vibrant designs, available in Youth, Women, and Men's sizing.",
    idealFor: "Sports teams, charities, events & schools",
    image: "/ranges/teamwear/custom-tracksuits.webp",
    images: [
      "/products/teamwear/custom-tracksuits/custom-tracksuits-1.webp",
      "/products/teamwear/custom-tracksuits/custom-tracksuits-2.webp",
      "/products/teamwear/custom-tracksuits/custom-tracksuits-3.webp",
      "/products/teamwear/custom-tracksuits/custom-tracksuits-4.webp",
      "/products/teamwear/custom-tracksuits/custom-tracksuits-5.webp",
    ],
    alt: "Custom Tracksuits",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester Fleece, Speedo or Scuba Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Full tracksuit: jacket & pants included",
      "100% polyester fleece, Speedo or Scuba fabric",
      "Fully dye sublimated, no limit on colors and logos",
      "High-quality durable construction",
      "Vibrant designs that stay bright wash after wash",
      "Ideal for sports teams, charities & events",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Sponsor logos & club crest",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-polo-shirts",
    productCode: "BHS-PS-001",
    name: "Custom Polo Shirts",
    description:
      "Built for comfort and style, Big Hope's Custom Polo Shirts are made from lightweight, moisture-wicking polyester with full dye-sublimation for unlimited design and color options. Perfect for sports teams, clubs, and corporate wear.",
    longDescription:
      "100% polyester (Mesh or Spandex options), fully dye sublimated with unlimited color options. Durable construction maintaining vibrant designs for sports teams, clubs, and corporate wear.",
    idealFor: "Sports teams, clubs & corporate wear",
    image: "/ranges/teamwear/custom-polo-shirts.webp",
    images: [
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-1.webp",
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-2.webp",
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-3.webp",
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-4.webp",
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-5.webp",
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-6.webp",
      "/products/teamwear/custom-polo-shirts/custom-polo-shirts-7.webp",
    ],
    alt: "Custom Polo Shirts",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester, Mesh or Spandex",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Lightweight moisture-wicking polyester",
      "Full dye-sublimation, unlimited design and color options",
      "Polo collar with button placket",
      "Available in mesh or spandex options",
      "Durable construction maintaining vibrant designs",
      "Ideal for sports teams, clubs & corporate wear",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Corporate branding & sponsor logos",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-t-shirts",
    productCode: "BHS-TT-001",
    name: "Custom T-Shirts",
    description:
      "Big Hope's Custom Crew Neck T-Shirts feature lightweight material offering breathability, comfort, and moisture control. Fully customizable with your own colors, designs, and logos, ideal for teams, brands, and events.",
    longDescription:
      "100% polyester interlock fabric or 100% cool dry micromesh polyester, fully dye sublimated with no limit on colors and logos. Perfect for sports teams, training, fan gear, events, or promotional use.",
    idealFor: "Sports teams, training, fan gear, events & promotional use",
    image: "/ranges/teamwear/custom-t-shirts.webp",
    images: [
      "/products/teamwear/custom-t-shirts/custom-t-shirts-1.webp",
      "/products/teamwear/custom-t-shirts/custom-t-shirts-2.webp",
      "/products/teamwear/custom-t-shirts/custom-t-shirts-3.webp",
      "/products/teamwear/custom-t-shirts/custom-t-shirts-4.webp",
      "/products/teamwear/custom-t-shirts/custom-t-shirts-5.webp",
    ],
    alt: "Custom T-Shirts",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester Interlock or Cool Dry Micromesh",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Lightweight, breathability, comfort & moisture control",
      "100% polyester interlock or cool dry micromesh",
      "Fully dye sublimated, no limit on colors and logos",
      "High-quality fabric maintains vibrant designs",
      "Crew neck design",
      "Ideal for sports teams, training, fan gear & events",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Brand & sponsor logos",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-quarter-zipper-ls",
    productCode: "BHS-QZL-001",
    name: "Custom 1/4 Zipper LS",
    description:
      "Big Hope's Custom long sleeve quarter zipper combines warmth, comfort, and mobility. Crafted from polyester double interlock, mesh or fleece, fully customizable with team logos.",
    longDescription:
      "Fully dye sublimated with unlimited color options. High-quality fabric that withstands wear, keeping designs vibrant and long-lasting, ideal for training, match day, and polished teamwear.",
    idealFor: "Sports teams, training wear & match day",
    image: "/ranges/teamwear/custom-quarter-zipper-ls.webp",
    images: [
      "/products/teamwear/custom-quarter-zipper-ls/custom-quarter-zipper-ls-1.webp",
      "/products/teamwear/custom-quarter-zipper-ls/custom-quarter-zipper-ls-2.webp",
      "/products/teamwear/custom-quarter-zipper-ls/custom-quarter-zipper-ls-3.webp",
      "/products/teamwear/custom-quarter-zipper-ls/custom-quarter-zipper-ls-4.webp",
      "/products/teamwear/custom-quarter-zipper-ls/custom-quarter-zipper-ls-5.webp",
    ],
    alt: "Custom 1/4 Zipper Long Sleeve",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester, Mesh or Fleece",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Long sleeve quarter-zip design",
      "100% polyester mesh or fleece",
      "Fully dye sublimated, unlimited color options",
      "High-quality fabric for vibrant, long-lasting designs",
      "Warmth, comfort & mobility combined",
      "Ideal for training, match day & polished teamwear",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Sponsor logos & club crest",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-1-4-zipper-ss",
    productCode: "BHS-QZS-001",
    name: "Custom 1/4 Zipper SS",
    description:
      "Big Hope's Custom Short sleeve quarter zipper merges warmth, comfort, and mobility. Constructed from polyester, mesh or customized fabric, fully customizable with team logos.",
    longDescription:
      "Fully dye sublimated with no limit on colors and logos. High-quality fabric maintains vibrant, long-lasting designs, ideal for sports teams and training wear.",
    idealFor: "Sports teams, training wear & match day",
    image: "/ranges/teamwear/custom-quarter-zipper-ss.webp",
    images: [
      "/products/teamwear/custom-1-4-zipper-ss/custom-1-4-zipper-ss-1.webp",
      "/products/teamwear/custom-1-4-zipper-ss/custom-1-4-zipper-ss-2.webp",
      "/products/teamwear/custom-1-4-zipper-ss/custom-1-4-zipper-ss-3.webp",
      "/products/teamwear/custom-1-4-zipper-ss/custom-1-4-zipper-ss-4.webp",
      "/products/teamwear/custom-1-4-zipper-ss/custom-1-4-zipper-ss-5.webp",
    ],
    alt: "Custom 1/4 Zipper Short Sleeve",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "100% Polyester, Mesh or Custom Fabric",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "Short sleeve quarter-zip design",
      "100% polyester mesh or customized fabric",
      "Fully dye sublimated, no limit on colors and logos",
      "High-quality fabric maintains vibrant designs",
      "Comfort & mobility combined",
      "Ideal for sports teams and training wear",
    ],
    customOptions: [
      "Unlimited colour combinations",
      "Team logos, names & numbers",
      "Sponsor logos & club crest",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },
  {
    slug: "custom-jackets",
    productCode: "BHS-CJ-001",
    name: "Custom Coach Jackets",
    description:
      "Premium custom jackets designed for teams, clubs, and brands. Fully personalized with colors, logos, names, and graphics. Available in lightweight water-resistant shells, waterproof rain jackets, and insulated puffer jackets.",
    longDescription:
      "Premium performance-grade polyester and nylon fabrics with high-quality stitching and reinforced seams. Customization via embroidery, heat transfer, or sublimation, available in men's, women's, and youth sizing.",
    idealFor: "Sports teams, clubs, schools & brands",
    image: "/ranges/teamwear/custom-coach-jackets.webp",
    images: [
      "/products/teamwear/custom-jackets/custom-jackets-1.webp",
      "/products/teamwear/custom-jackets/custom-jackets-2.webp",
      "/products/teamwear/custom-jackets/custom-jackets-3.webp",
      "/products/teamwear/custom-jackets/custom-jackets-4.webp",
      "/products/teamwear/custom-jackets/custom-jackets-5.webp",
    ],
    alt: "Custom Coach Jackets",
    sport: "Teamwear",
    sportSlug: "teamwear",
    fabric: "Premium Performance-Grade Polyester & Nylon",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Embroidery, heat transfer, or sublimation",
    },
    features: [
      "Premium performance-grade polyester and nylon",
      "High-quality stitching and reinforced seams",
      "Available in coach, rain, and puffer jacket styles",
      "Water-resistant or fully waterproof options",
      "Customization via embroidery, heat transfer, or sublimation",
      "Relaxed, athletic, and fitted cuts available",
    ],
    customOptions: [
      "Team logos, names & numbers",
      "Corporate & sponsor branding",
      "Embroidery or sublimation options",
      "Free design artwork",
      "Men's, women's & youth sizing",
    ],
  },

  // ── Accessories ───────────────────────────────────────────────────────
  {
    slug: "custom-bags",
    productCode: "BHS-BP-001",
    name: "Custom Bagpacks",
    description:
      "Durable custom team backpacks built for athletes and clubs. Fully personalized with team logos, names, and numbers.",
    longDescription:
      "Heavy-duty polyester/nylon fabric designed for strength, weather resistance, and daily use. Customization via embroidery, heat transfer, or sublimation. Reinforced stitching, tough zippers, and tear-resistant construction.",
    idealFor: "Sports teams, clubs, schools, travel, tournaments & training",
    image: "/ranges/accessories/custom-backpacks.webp",
    images: [
      "/products/accessories/custom-bags/custom-bags-1.webp",
      "/products/accessories/custom-bags/custom-bags-2.webp",
      "/products/accessories/custom-bags/custom-bags-3.webp",
      "/products/accessories/custom-bags/custom-bags-4.webp",
      "/products/accessories/custom-bags/custom-bags-5.webp",
    ],
    alt: "Custom Bagpacks",
    sport: "Accessories",
    sportSlug: "accessories",
    fabric: "Heavy-Duty Polyester / Nylon",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Custom sizing available",
      printing: "Embroidery, heat transfer or sublimation",
    },
    features: [
      "Heavy-duty polyester/nylon fabric",
      "Strength, weather resistance & daily use",
      "Reinforced stitching, tough zippers & tear-resistant construction",
      "Customization via embroidery, heat transfer, or sublimation",
      "Multiple compartments for storage",
      "Ideal for sports teams, clubs & schools",
    ],
    customOptions: [
      "Team logos, names & numbers",
      "Sponsor branding",
      "Embroidery or sublimation options",
      "Free design artwork",
      "Custom sizing available",
    ],
  },
  {
    slug: "custom-duffle-bags",
    productCode: "BHS-DB-001",
    name: "Custom Duffle Bags",
    description:
      "Durable custom duffle bags built for athletes and clubs. Fully personalized with team logos, names, and numbers.",
    longDescription:
      "Heavy-duty polyester/nylon fabric designed for strength, weather resistance, and daily use. Reinforced stitching, tough zippers, and tear-resistant construction, customization via embroidery, heat transfer, or sublimation.",
    idealFor: "Sports teams, clubs, schools, travel, tournaments & training",
    image: "/ranges/accessories/custom-duffle-bags.webp",
    images: [
      "/products/accessories/custom-duffle-bags/custom-duffle-bags-1.webp",
      "/products/accessories/custom-duffle-bags/custom-duffle-bags-2.webp",
      "/products/accessories/custom-duffle-bags/custom-duffle-bags-3.webp",
      "/products/accessories/custom-duffle-bags/custom-duffle-bags-4.webp",
      "/products/accessories/custom-duffle-bags/custom-duffle-bags-5.webp",
    ],
    alt: "Custom Duffle Bags",
    sport: "Accessories",
    sportSlug: "accessories",
    fabric: "Heavy-Duty Polyester / Nylon",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Custom sizing available",
      printing: "Embroidery, heat transfer or sublimation",
    },
    features: [
      "Heavy-duty polyester/nylon fabric",
      "Designed for strength, weather resistance & daily use",
      "Reinforced stitching, tough zippers & tear-resistant",
      "Customization via embroidery, heat transfer, or sublimation",
      "Spacious main compartment for equipment",
      "Ideal for sports teams, clubs & schools",
    ],
    customOptions: [
      "Team logos, names & numbers",
      "Sponsor branding",
      "Embroidery or sublimation options",
      "Free design artwork",
      "Custom sizing available",
    ],
  },
  {
    slug: "custom-socks",
    productCode: "BHS-CS-001",
    name: "Custom Socks",
    description:
      "Our custom socks are designed according to your exact requirements and best suited to match your team's colors. Empower your team with our custom socks.",
    longDescription:
      "High-performance blend of nylon, polyester, and spandex for durability, stretch, and moisture control. Reinforced heel and toe construction, available in youth, women's, and men's sizing.",
    idealFor: "Soccer clubs, school teams, leagues & training",
    image: "/ranges/accessories/custom-socks.webp",
    images: [
      "/products/accessories/custom-socks/custom-socks-1.webp",
      "/products/accessories/custom-socks/custom-socks-2.webp",
      "/products/accessories/custom-socks/custom-socks-3.webp",
      "/products/accessories/custom-socks/custom-socks-4.webp",
      "/products/accessories/custom-socks/custom-socks-5.webp",
    ],
    alt: "Custom Socks",
    sport: "Accessories",
    sportSlug: "accessories",
    fabric: "High-Performance Nylon / Polyester / Spandex Blend",
    specs: {
      minOrder: "10 pieces",
      turnaround: "2–3 wks (rush) / 2–3 wks (normal)",
      sizes: "Youth, Women, Men",
      printing: "Full-color dye-sublimation",
    },
    features: [
      "High-performance nylon, polyester & spandex blend",
      "Reinforced heel and toe construction",
      "Elastic cuff stays up during play",
      "Moisture-wicking for all-day comfort",
      "Team color customization",
      "Available in youth, women's & men's sizing",
    ],
    customOptions: [
      "Team colours & club crest",
      "Player name or number",
      "Sponsor logo placement",
      "Free design artwork",
      "Youth and adult sizing",
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string): Product[] {
  const product = getProductBySlug(slug);
  if (!product) return [];
  return allProducts
    .filter((p) => p.sportSlug === product.sportSlug && p.slug !== slug)
    .slice(0, 3);
}

export const soccerProducts = allProducts.filter(
  (p) => p.sportSlug === "soccer",
);
export const rugbyProducts = allProducts.filter((p) => p.sportSlug === "rugby");
export const basketballProducts = allProducts.filter(
  (p) => p.sportSlug === "basketball",
);
export const cricketProducts = allProducts.filter(
  (p) => p.sportSlug === "cricket",
);
export const footballProducts = allProducts.filter(
  (p) => p.sportSlug === "7v7-football",
);
export const baseballProducts = allProducts.filter(
  (p) => p.sportSlug === "baseball",
);
export const mmaProducts = allProducts.filter((p) => p.sportSlug === "mma");
export const teamwearProducts = allProducts.filter(
  (p) => p.sportSlug === "teamwear",
);
export const accessoriesProducts = allProducts.filter(
  (p) => p.sportSlug === "accessories",
);
